### ISSUE TITLE
Filtering Resources by Creator

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/rodan-client#106]
~~It would be nice if I could delete Generated Result Resources.~~

~~After running a few workflows, the resource list gets very cluttered and finding the resources I want to use becomes difficult.~~

Apparently we can't delete Generated Result Resources.  So, I think the next best thing would be to be able to filter by Resource creator.  That way, I can filter out all the generated resources and see only those resources that I personally uploaded.

**Comment by mrbannon** [comment]
It's best not to delete generated resources. Rather, these should be
filtered out by default. I think an issue exists for this.

**Comment by mrbannon** [comment]
Depends on https://github.com/DDMAL/Rodan/issues/425
