### ISSUE TITLE
Integrate ResourceList support

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/rodan-client#113]
ResourceLists in Rodan can be thought of as single Resources that encapsulate multiple individual Resources. This is how aggregate jobs will get their input. This exists in Rodan now...just need to start using it.

**Comment by ahankinson** [comment]
Can we simplify things by making every output a resource list, even if it only contains one element?

**Comment by mrbannon** [comment]
Ideally, yes. But that would be a rather large job on the Rodan side.

**Comment by deepio** [comment]
We have resource lists now
