### ISSUE TITLE
Resulting images downloadable as a single compressed file

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/rodan-client#133]
It would be great to be able to download a set of resulting images as a ZIP file from the RODAN client instead of downloading them one by one.

![screen shot 2016-10-19 at 3 52 08 pm](https://cloud.githubusercontent.com/assets/492229/19534994/081856f6-9614-11e6-8399-44ca43d0f59d.png)

**Comment by deepio** [comment]
With the multi-select feature, this is the current behavior since that was implemented.
