### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by musicus** [DDMAL/rodan-client#134]
Under "Setup Rodan server for the client" should there be a link to the _Rodan server_ repository/site? It only talks about the Rodan server administrator... Alternatively, the header could be named something else, since it seems to imply that instructions on how to set up the _Rodan server_ are to follow.

**Comment by deepio** [comment]
The Rodan repository will be converted into a docker project. All installation will now be in the form of docker files and shell scripts.
