### ISSUE TITLE
Add user in "Creator" column of resources

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/rodan-client#138]
The results of jobs are assigned with a "generated result" tag for the creator. This is pretty helpful to understand that this result was generated by Rodan and not uploaded by a user. However, when there are many users working at the same time, this generic tag makes pretty hard to find the results of a job submitted by a specific user. 

A second table could be useful, or adding the username as part of the "Generated result" tag.

**Comment by deepio** [comment]
![Screen Shot 2020-09-25 at 9 24 45 AM](https://user-images.githubusercontent.com/28245482/94272423-0ca6b400-ff11-11ea-8da3-0940e8150670.png)
I don't remember when this was added, but it was a while ago.
