### ISSUE TITLE
Can't delete resources

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/rodan-client#139]
I can't delete resources that I have uploaded. 

The Rodan client returns the message

![screen shot 2017-11-10 at 12 02 50 pm](https://user-images.githubusercontent.com/492229/32669624-2a1eca60-c60f-11e7-9c4a-be1c3ad6aa14.png)

The left pane stays in "1 of x requests pending". After refreshing the page, the resources are still in the list,

**Comment by deepio** [comment]
I don't have this error on the dev server. Can you give me some additional information? Lets meet about this.

**Comment by vigliensoni** [comment]
If I try to delete the resource

https://api.dev.rodan.simssa.ca/resource/a5b84b98-a10d-4665-8f51-d06bfb4725c0/

dev-rodan stays in "request pending" state



On Mon, Nov 13, 2017 at 11:56 AM, Alex Daigle <notifications@github.com>
wrote:
>
> I don't have this error on the dev server. Can you give me some
additional information? Lets meet about this.

**Comment by deepio** [comment]
The issue happens when a failed job is referencing the resource. Django was setup to disable the deletion of resources that are still being referenced, perhaps we should place a provision on failed jobs and delete them both simultaneously when trying to delete the resource first.
