### ISSUE TITLE
can't create new project

### ISSUE THREAD

**Issue by musicnerd** [DDMAL/rodan-client#143]
When I try to click on "create new project" I get a pop-up error and cannot continue:

Rodan Client has encountered an unexpected error.<br><br>text: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data<br>url: https://rodan.simssa.ca/rodan-client.min.js<br>line: 58587<br>column: 81

**Comment by deepio** [comment]
The response from nginx was a 502 error and therefore not json serializable. It was fixed in the private repository last year, where a duplicate issue existed.
