### ISSUE TITLE
Description and Name files should be larger

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/rodan-client#16]
Right now they're just small text boxes. Name fields should probably be bigger, and description fields should have larger width/height.

**Comment by musicus** [comment]
Yes, indeed, but the description should have a textarea field, which is different than a text input field.

**Comment by mrbannon** [comment]
Yes..I meant text area. Tx

**Comment by mrbannon** [comment]
this was fixed some time ago when i bootstrapped everything

**Comment by musicus** [comment]
:tiger2:: Grrrrrreat!
