### ISSUE TITLE
Fix position jobs when importing workflow

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/rodan-client#164]
The original position of the Rodan jobs is not preserved after "Importing workflow from file". See image for reference

<img width="557" alt="Screen Shot 2020-08-20 at 11 18 26 AM" src="https://user-images.githubusercontent.com/492229/90791178-e4ef7b00-e2d6-11ea-8530-68530c8a138c.png">

I don't know if this is not stored when Exporting the workflow or if it is not taking into account at importing time.

**Comment by JRegimbal** [comment]
It isn't stored when the workflow is exported. In fact positions are stored entirely separately from the workflow itself which has made this difficult to fix in the past since it would probably involve changes to the models itself.

**Comment by deepio** [comment]
I made a branch of Rodan which stores the position in the workflowjob model with the rest of the information for any specific job in a workflow. Importing and exporting has the information we need on the Rodan side, now we need to make the adjustments in the Rodan-Client.

![Screen Shot 2020-09-14 at 4 31 14 PM](https://user-images.githubusercontent.com/28245482/93135336-24c43b00-f6a8-11ea-95af-bcb55efac792.png)

**Comment by deepio** [comment]
What remains is the following:
- [x] make the client use the appearance field from the Rodan API for WFJs: a488879ff1f3a0ca06fb32bca4023fd632f8609c 
- [ ] make sure the same works for WFJ Groups:
- [ ] make sure the database will update its model by taking values from the coordinate set as default, making the migrations seamless.

**Comment by deepio** [comment]
Migration is built and ready to test: https://github.com/DDMAL/Rodan/compare/develop...Remove-Coordinate-Set-Models

**Comment by deepio** [comment]
Removed Coordinate Sets in:
Rodan-Client: 57ea1759648a2212b410f5e0b819f149b405d0ed
Rodan: https://github.com/DDMAL/Rodan/commit/6605967081dea2e2f5d9342f3f3c63a9b97150ca
