### ISSUE TITLE
Configuration info should exist at project root level

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/rodan-client#2]
Right now, config exists in a js file within web/js. This info should be defined at the project root and used as a parameter, OR...

The client could offer a form in which you specify the config!

**Comment by ahankinson** [comment]
https://github.com/DDMAL/RodanClient/blob/develop/rodan/app/Configuration.js

This is how we are doing it for rodan client

**Comment by mrbannon** [comment]
I was talking about the project root, not the web app root. However, I
guess that keeping it in the web app root is best.
