### ISSUE TITLE
Workflow Run Screen

### ISSUE THREAD

**Issue by musicus** [DDMAL/rodan-client#36]
There should be a description on what to do when one is at the *Workflow Run* screen. It is not intuitive that *NoteRest Indexer - MusicXML* (__Label__) needs to be selected, and that the resource (__Name__) needs to be selected, until after they have been selected, before a workflow can be successfully run.

**Comment by mrbannon** [comment]
Covered by #18

**Comment by musicus** [comment]
But #18 was closed, and so is this one :-/...

**Comment by mrbannon** [comment]
According to the history, #18 was never closed. I just closed #36 because
#18 takes care of it.
