### ISSUE TITLE
WorkflowBuilder GUI state machine should be frame driven, not event driven

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/rodan-client#45]
Right now the canvas updates on events. Better idea would be frames. To make things smooth, could lock frame rate to something low, or make it adjustable.

**Comment by ahankinson** [comment]
Would any of these help?

http://www.html5rocks.com/en/tutorials/canvas/performance/

**Comment by mrbannon** [comment]
Nah, but thanks. I know how to do it. I just have to do it. :)

**Comment by mrbannon** [comment]
Basics done. Frame rate is currently not controlled...might want to do that to lighten load.
